// src/routes/NavBar.svelte
<script>
    import { hexlogo } from "../assets";
</script>


<div>
    <nav class=" flex justify-between w-[100%] h-auto">
        <div>
            <a href="/"><img src={hexlogo} alt="hex logo" class="navlogo" /></a>
        </div>
        <div>
            <a href="/goals">goals</a>
            <a href="/about">about</a>
        </div>
    </nav>
</div>

<style>

</style>

// src/components/Navbar.jsx
import React from "react";
import { Link } from "react-router-dom";
import { hexlogo } from "../assets";
import "./Navbar.css";

function Navbar() {
  return (
    <>
      <nav className=" flex justify-between w-[100%] h-auto">
        <div>
          <Link to="/">
            <img src={hexlogo} className=" Navlogo"/>
          </Link>
        </div>
        <div className=" pr-5">
          <ul className=" pt-4 h-full flex">
            <li className=" p-3 text-3xl">
              <Link to="/goals" className=" text-center">Goals</Link>
            </li>
          </ul>
        </div>
        
      </nav>
    </>
  );
}

export default Navbar;
